### ISSUE TITLE
Root URL Admin Site 301 Response

### ISSUE THREAD

**Issue by ml394** [ahmedaljawahiry/django-admin-site-search#11]
When the admin site is mapped to the root URL path, the `adminSearchPath` returns a 301 response due to a missing trailing slash `/`. As a result, the query `q` is not passed through to the redirected URL and the `search` method returns 0 values.

![image](https://user-images.githubusercontent.com/6338648/232154958-c4ffe9a9-2c40-4fd6-a15d-21f3043b2511.png)

## How to recreate

Set the admin site path to the root URL of the site in the project `urls.py`
```
urlpatterns = [
    path('', admin.site.urls)
]
```

## Steps to resolve

search.js:35
```
const adminSearchPath = adminPath ? `/${adminPath}/search/` : '/search';
```

Adding the trailing slash returns the correct 200 response along with the full search results.
```
const adminSearchPath = adminPath ? `/${adminPath}/search/` : '/search/';
```

![image](https://user-images.githubusercontent.com/6338648/232155194-ec7aad22-2a40-4cb1-8b53-aac188f646e8.png)

**Comment by ahmedaljawahiry** [comment]
Thanks for raising this, and for the proposed solution! Have implemented and published in [0.3.2](https://github.com/ahmedaljawahiry/django-admin-site-search/commit/7c4dac81e4105750c13b1ed202cab0f0845b0488)

**Comment by ml394** [comment]
No problem @ahmedaljawahiry! Really enjoying the library by the way, using it across a ton of projects!

**Comment by ahmedaljawahiry** [comment]
Great to hear!
