### ISSUE TITLE
Search only working on the admin index page

### ISSUE THREAD

**Issue by tfeldmann** [ahmedaljawahiry/django-admin-site-search#13]
Thank you for this project, it really comes in handy!

I think something might be wrong with how the search url is generated. My project is a bit different because it uses "/" as the path to the admin:

```python
path("", admin.site.urls, name="home"),
```

So when I'm searching on the `admin:index` page the search url is: `/search/?q=asd`.
Now when I open the user groups it searches `/auth/search/?q=asd` and says "An unexpected error occured".

Is there a configuration option for the search url?

**Comment by ahmedaljawahiry** [comment]
Happy to hear you're enjoying the project, and thanks for raising the issue!

Looks like the [current](https://github.com/ahmedaljawahiry/django-admin-site-search/blob/main/admin_site_search/static/admin_site_search/search.js#L34) approach for determining the search path has hit its limit! I anticipated we'd need to pass this explicitly.

[This PR](https://github.com/ahmedaljawahiry/django-admin-site-search/pull/14) should address the issue. Though, the path is still set to `search/`, without an override. This may be an issue if anyone already has a page at `search/` - I'll make a note to get this configurable.

Will look to get https://github.com/ahmedaljawahiry/django-admin-site-search/pull/14 merged and released asap

**Comment by ahmedaljawahiry** [comment]
Changes above released in [0.4.0](https://pypi.org/project/django-admin-site-search/0.4.0/), along with an option for configuring the path ([readme updated](https://github.com/ahmedaljawahiry/django-admin-site-search#2-add-view)).

Closing this, but let me know if there's any issues!
