### ISSUE TITLE
Object ID prefix

### ISSUE THREAD

**Issue by pawcio0928** [ahmedaljawahiry/django-admin-site-search#17]
Hey,

in my code I am using helper method to add prefix to ID to easily know from what model it comes.
Something like that: 

```
class testmodel(models.Model):

    def product_id(self):

       return f'YNT{self.id}'

```

is it possible to add functionalities to the search bar that will also see help methods? 

Thanks!

**Comment by ahmedaljawahiry** [comment]
Hey!

Thanks for raising.

To clarify - do you mean you want to see those IDs (or whatever property) in the search results? Or, you want the search functionality to work for values of that property?

FYI - I'm away this week. Will be able to comment, but back to code/features next week.

**Comment by pawcio0928** [comment]
Hey,
Thanks for your

**Comment by pawcio0928** [comment]
Hey, 

thanks for your feedback. 

Initially I want just to have ability to find my custom IDs. 

Second option also sounds interesting and would be nice to have it too. 

Thanks for your help.

**Comment by ahmedaljawahiry** [comment]
Ah, gotcha.

If those IDs are set inside of a method/property, then it's not possible unfortunately.

The search is done at the database level. To search dynamic properties, you'd have to: load all instances, call the method, then search on the results. This would be too inefficient. You could potentially do this yourself, by overriding the `match_objects` method ("customisation" in [docs](https://github.com/ahmedaljawahiry/django-admin-site-search/blob/main/README.md)), but I wouldn't recommend it.

If your `product_id`, or `product_id_prefix`, was a database field then it's possible (would probably work by default).

**Comment by ahmedaljawahiry** [comment]
Closing for now, but let me know if anything else comes up.
