### ISSUE TITLE
How to exclude certain models?

### ISSUE THREAD

**Issue by kevinrenskers** [ahmedaljawahiry/django-admin-site-search#21]
At the moment every model that's registered with the admin site is searched through, but I have some models that I'd like to exclude. They're not interesting to search through and it'll definitely help speed up the search.

As an aside, are there ways to speed up the search? Every query takes about 5 seconds to complete on my local machine, and it'll be slower on the production server for sure.

**Comment by kevinrenskers** [comment]
Ah, found it.

```python
class MyAdminSite(AdminSiteSearchView, admin.AdminSite):
    def match_objects(self, query, model_class, model_fields):
        if model_class in [ModelOne, ModelTwo]:
            return Q()
        return super().match_objects(query, model_class, model_fields)
```

And yes, this has already brought the search down to less than 2 seconds :)

**Comment by ahmedaljawahiry** [comment]
Yep - that's the way 👍 

I've pondered on making this a bit simpler, maybe with an attribute on the admin class. Will be much simpler to do that once there's some implementation for https://github.com/ahmedaljawahiry/django-admin-site-search/issues/22, so will revisit then.

**Comment by ahmedaljawahiry** [comment]
Closing as there's now a few ways to accomplish this:
- `admin_search_fields`: search delegated to a ModelAdmin's `get_search_results` / `search_fields`.
- `model_char_fields`: override `match_objects` or `get_model_class`.
