### ISSUE TITLE
Idea: use the ModelAdmin's search_fields

### ISSUE THREAD

**Issue by kevinrenskers** [ahmedaljawahiry/django-admin-site-search#22]
All of my models that I want to have searchable already have a custom ModelAdmin. And all of them have a `search_fields` property which determines which fields I want to have searchable. It would be super nice if django-admin-site-search could stick to this as well, so that search happens in the fields that I want to be searchable, no more and no less (solving #21). This should give a performance boost by not using literally every `CharField` subclass, and should hopefully make searching through relations automatic as well (closing #20).

Great project by the way, the results look super slick.

**Comment by ahmedaljawahiry** [comment]
Thanks for the idea, and glad you like the project!

This is a great suggestion - it makes total sense. 

The current approach is definitely "greedy", but I like that you get results out-of-the-box without much configuration. I've hesitated in adding further settings (to avoid the complexity), but this seems like an easy win. 

I'll have a think about implementation and see if I can get round to it soon. Suspect it'll be an option, set at the class level, to specify the search method. Something like:
```
site_search_method = "model_char_fields" | "admin_search_fields" | etc.
```

**Comment by ahmedaljawahiry** [comment]
Just a note to say I haven't forgotten about this! Busy couple of months, but hope to get to it soon 🙏

**Comment by ahmedaljawahiry** [comment]
Released in 1.0.0 👉  https://github.com/ahmedaljawahiry/django-admin-site-search/releases/tag/1.0.0

**Comment by kevinrenskers** [comment]
Thanks! I'll play around with this this week. One thing I am immediately thinking about: it's not so nice to have to add the `site_search_method` config to every model admin everywhere. Would it be a good idea to be able to set the default search method in settings.py?

**Comment by ahmedaljawahiry** [comment]
> not so nice to have to add the `site_search_method` config to every model admin everywhere. Would it be a good idea to be able to set the default search method in settings.py?

`site_search_method` is only defined once, under the `AdminSite` class (where `AdminSiteSearchView` is), not under each `ModelAdmin`.

I did consider adding to `settings.py`, but prefer keep it closer to home. 

Interesting point though - could look into having overrides per admin/model.

**Comment by kevinrenskers** [comment]
Ah my bad, somehow I assumed it was per ModelAdmin instance.

**Comment by kevinrenskers** [comment]
It works beautifully and I was able to get rid of a lot of custom setup code :)
