### ISSUE TITLE
🔧 Update `pyproject.toml` File and Configuration

### ISSUE THREAD

**Issue by ARYAN-NIKNEZHAD** [ahmedaljawahiry/django-admin-site-search#31]
### Description:
This Django package currently lacks a `pyproject.toml` file config, which is becoming increasingly important for modern Python packaging and dependency management. The absence of this file means we're missing out on several benefits, including:

1. **Standardized Project Metadata**: `pyproject.toml` allows us to define project metadata in a standardized format, which can improve compatibility with various tools and packaging systems.
  
2. **Build System Specification**: Without `pyproject.toml`, we cannot specify build system requirements, which can cause issues with building or installing the package using modern tools.

3. **Tool Configuration**: Many tools, such as `poetry`, rely on `pyproject.toml` for their configuration. This omission could lead to inconsistent development practices and lower code quality.

4. **Dependency Management**: `pyproject.toml` supports specifying build dependencies and project requirements in a unified way, reducing complexity and improving reproducibility.

#### Action Items:
- Create a `pyproject.toml` file at the root of the project directory.
- Configure `poetry` within the `pyproject.toml` to handle dependencies and project settings.
- Update documentation to reflect the new configuration file and any changes in development practices.

This update will streamline our development process, improve tooling compatibility, and align with modern Python packaging standards.

**Comment by ahmedaljawahiry** [comment]
Thanks for raising (🤖?), but no plans to extend the existing `pyproject.toml`.
