### ISSUE TITLE
📦 Add `Commitizen` for Commit Message Standardization and Versioning

### ISSUE THREAD

**Issue by ARYAN-NIKNEZHAD** [ahmedaljawahiry/django-admin-site-search#32]
**Summary**:  
The current package lacks standardized commit message formatting and automated versioning. To improve consistency and streamline our release process, I propose integrating [Commitizen](https://github.com/commitizen-tools/commitizen) into our development workflow. Commitizen enforces conventional commit messages and automates the versioning process, making it easier to manage releases and generate changelogs.

### 1. Commit Message Standardization:
   - Commitizen helps enforce a consistent commit message format across the project. Adhering to the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) specification will make it easier to understand the purpose of each commit, which is essential for collaboration and code reviews.
   - Example of Conventional Commit message structure:
     - `feat`: A new feature.
     - `fix`: A bug fix.
     - `docs`: Documentation-only changes.
     - `style`: Changes that do not affect the meaning of the code (e.g., formatting).
     - `refactor`: A code change that neither fixes a bug nor adds a feature.
     - `test`: Adding or correcting tests.
     - `chore`: Changes to the build process or auxiliary tools and libraries.

### 2. Automated Versioning:
   - Commitizen can automatically bump the version of the project based on the commit messages. This reduces manual errors in versioning and ensures that version numbers reflect the significance of changes made.
   - Version bumps are categorized as:
     - `major`: Breaking changes.
     - `minor`: New features.
     - `patch`: Bug fixes.

### 3. Changelog Generation:
   - Commitizen can automatically generate a `CHANGELOG.md` file based on the commit history. This ensures that our changelog is always up-to-date and accurately reflects the changes made between releases.
   
### 4. Benefits:
   1. Consistency: Enforces a uniform commit message format across the project.

   2. Automation: Automates version bumps and changelog generation, reducing the chance of human error.

   3. Improved Collaboration: Clear commit messages make it easier for team members to understand the changes being made.

**Comment by ahmedaljawahiry** [comment]
Thanks for raising (🤖?), but not interested right now
