### ISSUE TITLE
Compataility with django-constanse

### ISSUE THREAD

**Issue by mohamedmansor** [ahmedaljawahiry/django-admin-site-search#6]
Search will raise an `LookupError: App 'constance' doesn't have a 'Config' model.` error when the [django-constance](https://django-constance.readthedocs.io/en/latest/) is used due the model name is `Constance` but it's registered in the admin with `Config` Name instead. 

https://github.com/jazzband/django-constance/blob/master/constance/admin.py

**Comment by ahmedaljawahiry** [comment]
@mohamedmansor - should be fixed in 0.3.0; let me know if not!
